/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esocial.userinterface;

import esocial.people.Empregado;
import esocial.people.Empregador;
import javax.swing.JOptionPane;

/**
 *
 * @author Izadora
 */
public class CadastroEmpregado extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEmpregado
     */
    private Empregador[] listaEmpregadores;
    
    public CadastroEmpregado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadEmpregadoLabel = new javax.swing.JLabel();
        telefoneEmpregadoLabel = new javax.swing.JLabel();
        nomeEmpregadoLabel = new javax.swing.JLabel();
        cpfEmpregadoLabel = new javax.swing.JLabel();
        telefoneEmpregadoLabel1 = new javax.swing.JLabel();
        telefoneEmpregadoLabel2 = new javax.swing.JLabel();
        numeroNISEmpregadoLabel = new javax.swing.JLabel();
        numCarteiraDeTrabalhoEmpregadoLabel = new javax.swing.JLabel();
        corEmpregadoLabel = new javax.swing.JLabel();
        escolaridadeEmpregadoLabel = new javax.swing.JLabel();
        dataAdmissaoEmpregadoLabel = new javax.swing.JLabel();
        salarioEmpregadoLabel = new javax.swing.JLabel();
        nomeEmpregadoTexto = new javax.swing.JTextField();
        telefoneEmpregadoTexto = new javax.swing.JFormattedTextField();
        dataDeAdmissaoEmpregadoTexto = new javax.swing.JFormattedTextField();
        cpfEmpregadoTexto = new javax.swing.JFormattedTextField();
        dataDeNascimentoEmpregadoTexto = new javax.swing.JFormattedTextField();
        emailEmpregadoTexto = new javax.swing.JTextField();
        pesquisarEmpregadoButton = new javax.swing.JButton();
        excluirEmpregadoButton = new javax.swing.JButton();
        casastrarEmpregadoButton = new javax.swing.JButton();
        escolaridadeEmpregadoComboBox = new javax.swing.JComboBox<>();
        corEmpregadoComboBox = new javax.swing.JComboBox<>();
        salarioEmpregadoTexto = new javax.swing.JFormattedTextField();
        numeroNISEmpregadoTexto = new javax.swing.JFormattedTextField();
        numeroCarteiraDeTrabalhoEmpregadoTexto = new javax.swing.JTextField();
        nomeEmpregadorLabel = new javax.swing.JLabel();
        nomeEmpregadorTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cadEmpregadoLabel.setText("Cadastro de empregados");

        telefoneEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telefoneEmpregadoLabel.setText("Telefone ");

        nomeEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomeEmpregadoLabel.setText("Nome do empregado");

        cpfEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpfEmpregadoLabel.setText("Cpf ");

        telefoneEmpregadoLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telefoneEmpregadoLabel1.setText("Email");

        telefoneEmpregadoLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telefoneEmpregadoLabel2.setText("Data de nascimento");

        numeroNISEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroNISEmpregadoLabel.setText("Número NIS");

        numCarteiraDeTrabalhoEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numCarteiraDeTrabalhoEmpregadoLabel.setText("Número carteira de trabalho");

        corEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        corEmpregadoLabel.setText("Cor");

        escolaridadeEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        escolaridadeEmpregadoLabel.setText("Escolaridade");

        dataAdmissaoEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dataAdmissaoEmpregadoLabel.setText("Data de admissão");

        salarioEmpregadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salarioEmpregadoLabel.setText("Salário");

        nomeEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpregadoTextoActionPerformed(evt);
            }
        });

        try {
            telefoneEmpregadoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneEmpregadoTextoActionPerformed(evt);
            }
        });

        try {
            dataDeAdmissaoEmpregadoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataDeAdmissaoEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeAdmissaoEmpregadoTextoActionPerformed(evt);
            }
        });

        try {
            cpfEmpregadoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfEmpregadoTextoActionPerformed(evt);
            }
        });

        try {
            dataDeNascimentoEmpregadoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataDeNascimentoEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeNascimentoEmpregadoTextoActionPerformed(evt);
            }
        });

        emailEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEmpregadoTextoActionPerformed(evt);
            }
        });

        pesquisarEmpregadoButton.setText("Pesquisar");
        pesquisarEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarEmpregadoButtonActionPerformed(evt);
            }
        });

        excluirEmpregadoButton.setText("Excluir");
        excluirEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEmpregadoButtonActionPerformed(evt);
            }
        });

        casastrarEmpregadoButton.setText("Cadastrar");
        casastrarEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casastrarEmpregadoButtonActionPerformed(evt);
            }
        });

        escolaridadeEmpregadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analfabeto:", "Ensino fundamental incompleto: ", "Ensino fundamental completo: ", "Ensino médio incompleto: ", "Ensino médio completo: ", "Superior completo (ou Graduação): ", "Pós-Graduação: ", "Mestrado: ", "Doutorado: ", "Pòs-Doutorado (PhD): " }));

        corEmpregadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branca", "Amarela", "Parda ", "Preta", "Indígena" }));

        salarioEmpregadoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        salarioEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioEmpregadoTextoActionPerformed(evt);
            }
        });

        try {
            numeroNISEmpregadoTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        numeroNISEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroNISEmpregadoTextoActionPerformed(evt);
            }
        });

        numeroCarteiraDeTrabalhoEmpregadoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCarteiraDeTrabalhoEmpregadoTextoActionPerformed(evt);
            }
        });

        nomeEmpregadorLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nomeEmpregadorLabel.setText("Nome do empregador");

        nomeEmpregadorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpregadorTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(cadEmpregadoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeEmpregadoLabel)
                            .addComponent(cpfEmpregadoLabel)
                            .addComponent(telefoneEmpregadoLabel)
                            .addComponent(numeroNISEmpregadoLabel)
                            .addComponent(corEmpregadoLabel)
                            .addComponent(dataAdmissaoEmpregadoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataDeAdmissaoEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(telefoneEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpfEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(corEmpregadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroNISEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salarioEmpregadoLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(salarioEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escolaridadeEmpregadoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(escolaridadeEmpregadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telefoneEmpregadoLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(dataDeNascimentoEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pesquisarEmpregadoButton)
                                        .addGap(47, 47, 47)
                                        .addComponent(excluirEmpregadoButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numCarteiraDeTrabalhoEmpregadoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numeroCarteiraDeTrabalhoEmpregadoTexto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telefoneEmpregadoLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomeEmpregadorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(casastrarEmpregadoButton)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cadEmpregadoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpregadoLabel)
                    .addComponent(nomeEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfEmpregadoLabel)
                    .addComponent(telefoneEmpregadoLabel2)
                    .addComponent(cpfEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDeNascimentoEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneEmpregadoLabel1)
                    .addComponent(telefoneEmpregadoLabel)
                    .addComponent(telefoneEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroNISEmpregadoLabel)
                    .addComponent(numCarteiraDeTrabalhoEmpregadoLabel)
                    .addComponent(numeroNISEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroCarteiraDeTrabalhoEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corEmpregadoLabel)
                    .addComponent(escolaridadeEmpregadoLabel)
                    .addComponent(escolaridadeEmpregadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corEmpregadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataAdmissaoEmpregadoLabel)
                    .addComponent(salarioEmpregadoLabel)
                    .addComponent(dataDeAdmissaoEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpregadorLabel)
                    .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarEmpregadoButton)
                    .addComponent(excluirEmpregadoButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(391, Short.MAX_VALUE)
                    .addComponent(casastrarEmpregadoButton)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpregadoTextoActionPerformed

    private void telefoneEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneEmpregadoTextoActionPerformed

    private void dataDeAdmissaoEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeAdmissaoEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDeAdmissaoEmpregadoTextoActionPerformed

    private void cpfEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfEmpregadoTextoActionPerformed

    private void dataDeNascimentoEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeNascimentoEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDeNascimentoEmpregadoTextoActionPerformed

    private void emailEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEmpregadoTextoActionPerformed

    private void salarioEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioEmpregadoTextoActionPerformed

    private void numeroNISEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroNISEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroNISEmpregadoTextoActionPerformed

    private void numeroCarteiraDeTrabalhoEmpregadoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCarteiraDeTrabalhoEmpregadoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCarteiraDeTrabalhoEmpregadoTextoActionPerformed

    private void casastrarEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casastrarEmpregadoButtonActionPerformed
        // TODO add your handling code here:
        Empregado novoEmpregado;
        novoEmpregado = new Empregado((String) dataDeNascimentoEmpregadoTexto.getValue(), 
                (String) numeroNISEmpregadoTexto.getValue(),
                (String) corEmpregadoComboBox.getSelectedItem(),
                (String) escolaridadeEmpregadoComboBox.getSelectedItem(),
                numeroCarteiraDeTrabalhoEmpregadoTexto.getText(),
                (String) dataDeAdmissaoEmpregadoTexto.getValue(),
                salarioEmpregadoTexto.getValue() != null ?
                        ((Number) salarioEmpregadoTexto.getValue())
                                .floatValue() : 0.0f,
                (String) cpfEmpregadoTexto.getValue(),
                nomeEmpregadoTexto.getText().toUpperCase(), 
                (String) telefoneEmpregadoTexto.getValue(),
                emailEmpregadoTexto.getText());
        
        addEmpregado(novoEmpregado);     
    }//GEN-LAST:event_casastrarEmpregadoButtonActionPerformed

    private void addEmpregado(Empregado novoEmpregado) {
        Empregador empregador = buscarEmpregador();
        if (empregador != null) {
            if (empregador.temEmpregado(novoEmpregado)) {
                JOptionPane.showMessageDialog(null, "Empregado já existe no cadastro.");
                limparTela();
                return;
            }
        
            if (empregador.adicionarEmpregado(novoEmpregado)) {
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso.");
                limparTela();
                return;
            }
            
            JOptionPane.showMessageDialog(null, "Falha no cadastro.");
            limparTela();
        } else {
            JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
        }
    }
    
    private Empregador buscarEmpregador() {
        for (Empregador empregador : listaEmpregadores)
            if (empregador != null && empregador.getNome()
                    .equals(nomeEmpregadorTexto.getText().toUpperCase()))
                return empregador;

        return null;
    }
    
    private void pesquisarEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarEmpregadoButtonActionPerformed
        // TODO add your handling code here:
        Empregador empregador = buscarEmpregador();
        
        if (empregador != null) {
            Empregado empregado = empregador.buscarEmpregado(nomeEmpregadoTexto.getText());
            if (empregado != null) {
                cpfEmpregadoTexto.setValue(empregado.getCpf());
                telefoneEmpregadoTexto.setValue(empregado.getTelefone());
                emailEmpregadoTexto.setText(empregado.getEmail()); 
                dataDeNascimentoEmpregadoTexto.setValue(empregado.getDataNascimento());
                numeroNISEmpregadoTexto.setValue(empregado.getNumeroNIS());
                numeroCarteiraDeTrabalhoEmpregadoTexto.setText(empregado.getNumCarteiraDeTrabalho());
                corEmpregadoComboBox.setSelectedItem(empregado.getCor());
                escolaridadeEmpregadoComboBox.setSelectedItem(empregado.getEscolaridade());
                dataDeAdmissaoEmpregadoTexto.setValue(empregado.getDataAdmissao());
                salarioEmpregadoTexto.setValue(empregado.getSalario()); 
                JOptionPane.showMessageDialog(null, "Empregado encontrado.");
            } else {
                JOptionPane.showMessageDialog(null, "Empregado não encontrado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
        }
    }//GEN-LAST:event_pesquisarEmpregadoButtonActionPerformed

    private void excluirEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEmpregadoButtonActionPerformed
        // TODO add your handling code here:
        Empregador empregador = buscarEmpregador();
        
        if (empregador != null) {
            if (empregador.removerEmpregado(nomeEmpregadoTexto.getText())) {
                limparTela();
                return;
            }
            
            JOptionPane.showMessageDialog(null, "Empregado não encontrado.");
        } else {
            JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
        }
    }//GEN-LAST:event_excluirEmpregadoButtonActionPerformed

    private void nomeEmpregadorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpregadorTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpregadorTextoActionPerformed
    
        private void pesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }  
            
     private void limparTela() {
        nomeEmpregadoTexto.setText(null);
        cpfEmpregadoTexto.setValue(null);
        telefoneEmpregadoTexto.setValue(null);
        emailEmpregadoTexto.setText(null); 
        dataDeNascimentoEmpregadoTexto.setValue(null);
        numeroNISEmpregadoTexto.setValue(null);
        numeroCarteiraDeTrabalhoEmpregadoTexto.setText(null);
        corEmpregadoComboBox.setSelectedIndex(-1);
        escolaridadeEmpregadoComboBox.setSelectedIndex(-1);
        dataDeAdmissaoEmpregadoTexto.setValue(null);
        salarioEmpregadoTexto.setValue(null);
        nomeEmpregadorTexto.setText(null);
    }    

    public void setListaEmpregadores(Empregador[] listaEmpregadores) {
        this.listaEmpregadores = listaEmpregadores;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CadastroEmpregado cadastroEmpregado = new CadastroEmpregado();
                cadastroEmpregado.setListaEmpregadores(MenuPrincipal.getListaEmpregadores());
                cadastroEmpregado.setVisible(true);
                cadastroEmpregado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadEmpregadoLabel;
    private javax.swing.JButton casastrarEmpregadoButton;
    private javax.swing.JComboBox<String> corEmpregadoComboBox;
    private javax.swing.JLabel corEmpregadoLabel;
    private javax.swing.JLabel cpfEmpregadoLabel;
    private javax.swing.JFormattedTextField cpfEmpregadoTexto;
    private javax.swing.JLabel dataAdmissaoEmpregadoLabel;
    private javax.swing.JFormattedTextField dataDeAdmissaoEmpregadoTexto;
    private javax.swing.JFormattedTextField dataDeNascimentoEmpregadoTexto;
    private javax.swing.JTextField emailEmpregadoTexto;
    private javax.swing.JComboBox<String> escolaridadeEmpregadoComboBox;
    private javax.swing.JLabel escolaridadeEmpregadoLabel;
    private javax.swing.JButton excluirEmpregadoButton;
    private javax.swing.JLabel nomeEmpregadoLabel;
    private javax.swing.JTextField nomeEmpregadoTexto;
    private javax.swing.JLabel nomeEmpregadorLabel;
    private javax.swing.JTextField nomeEmpregadorTexto;
    private javax.swing.JLabel numCarteiraDeTrabalhoEmpregadoLabel;
    private javax.swing.JTextField numeroCarteiraDeTrabalhoEmpregadoTexto;
    private javax.swing.JLabel numeroNISEmpregadoLabel;
    private javax.swing.JFormattedTextField numeroNISEmpregadoTexto;
    private javax.swing.JButton pesquisarEmpregadoButton;
    private javax.swing.JLabel salarioEmpregadoLabel;
    private javax.swing.JFormattedTextField salarioEmpregadoTexto;
    private javax.swing.JLabel telefoneEmpregadoLabel;
    private javax.swing.JLabel telefoneEmpregadoLabel1;
    private javax.swing.JLabel telefoneEmpregadoLabel2;
    private javax.swing.JFormattedTextField telefoneEmpregadoTexto;
    // End of variables declaration//GEN-END:variables
}
