/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esocial.userinterface;

import esocial.people.Empregador;
import javax.swing.JOptionPane;

/**
 *
 * @author Izadora
 */
public class CadastroEmpregador extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEmpregador
     */
    private Empregador[] listaEmpregador;
       
    public CadastroEmpregador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nomeEmpregadorLabel = new javax.swing.JLabel();
        cpfEmpregadorLabel = new javax.swing.JLabel();
        telefoneEmpregadorLabel = new javax.swing.JLabel();
        emailEmpregadorLabel = new javax.swing.JLabel();
        pesquisarEmpregadorButton = new javax.swing.JButton();
        casastrarEmpregadorButton = new javax.swing.JButton();
        excluirEmpregadorButton = new javax.swing.JButton();
        nomeEmpregadorTexto = new javax.swing.JTextField();
        emailEmpregadorTexto = new javax.swing.JTextField();
        cpfEmpregadorTexto = new javax.swing.JFormattedTextField();
        telefoneEmpregadorTexto = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de empregador");

        nomeEmpregadorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomeEmpregadorLabel.setText("Nome do empregador");

        cpfEmpregadorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpfEmpregadorLabel.setText("Cpf");

        telefoneEmpregadorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telefoneEmpregadorLabel.setText("Telefone");

        emailEmpregadorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailEmpregadorLabel.setText("Email");

        pesquisarEmpregadorButton.setText("Pesquisar");
        pesquisarEmpregadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarEmpregadorButtonActionPerformed(evt);
            }
        });

        casastrarEmpregadorButton.setText("Cadastrar");
        casastrarEmpregadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casastrarEmpregadorButtonActionPerformed(evt);
            }
        });

        excluirEmpregadorButton.setText("Excluir");
        excluirEmpregadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEmpregadorButtonActionPerformed(evt);
            }
        });

        try {
            cpfEmpregadorTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneEmpregadorTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(casastrarEmpregadorButton)
                .addGap(51, 51, 51)
                .addComponent(pesquisarEmpregadorButton)
                .addGap(57, 57, 57)
                .addComponent(excluirEmpregadorButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeEmpregadorLabel)
                    .addComponent(cpfEmpregadorLabel)
                    .addComponent(emailEmpregadorLabel)
                    .addComponent(telefoneEmpregadorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(telefoneEmpregadorTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(cpfEmpregadorTexto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(75, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpregadorLabel)
                    .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfEmpregadorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneEmpregadorLabel)
                    .addComponent(telefoneEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailEmpregadorLabel)
                    .addComponent(emailEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirEmpregadorButton)
                    .addComponent(pesquisarEmpregadorButton)
                    .addComponent(casastrarEmpregadorButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casastrarEmpregadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casastrarEmpregadorButtonActionPerformed
        // TODO add your handling code here:
    Empregador novoEmpregador;
    novoEmpregador = new Empregador((String) cpfEmpregadorTexto.getValue(), 
            nomeEmpregadorTexto.getText().toUpperCase(), 
            (String) telefoneEmpregadorTexto.getValue(), 
            emailEmpregadorTexto.getText()); 
    
    addEmpregador(novoEmpregador);
    }//GEN-LAST:event_casastrarEmpregadorButtonActionPerformed

    private void addEmpregador(Empregador novoEmpregador) {
        for (Empregador empregador : this.listaEmpregador) {
            if (empregador != null && (empregador.getNome()
                    .equals(novoEmpregador.getNome()) 
                    || empregador.getCpf().equals(novoEmpregador.getCpf()))) {
                JOptionPane.showMessageDialog(null, 
                        "Empregador já existe no cadastro.");
                limparTela();
                return;
            }
        }
        
        for (int i = 0; i < listaEmpregador.length; i++) {
            if (listaEmpregador[i] == null) {
                listaEmpregador[i] = novoEmpregador;
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso.");
                limparTela();
                return;
            }
        }
        
        JOptionPane.showMessageDialog(null, "Falha no cadastro.");
        limparTela();
    }
    
    private void pesquisarEmpregadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarEmpregadorButtonActionPerformed
        // TODO add your handling code here:
        for (Empregador empregador : this.listaEmpregador) {
            if (empregador != null && nomeEmpregadorTexto.getText()
                    .toUpperCase().equals(empregador.getNome())) {
                cpfEmpregadorTexto.setValue(empregador.getCpf());
                telefoneEmpregadorTexto.setValue(empregador.getTelefone());
                emailEmpregadorTexto.setText(empregador.getEmail());
                JOptionPane.showMessageDialog(null, "Empregador encontrado.");
                return;
            }
        }
        
        JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
    }//GEN-LAST:event_pesquisarEmpregadorButtonActionPerformed

    private void excluirEmpregadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEmpregadorButtonActionPerformed
        // TODO add your handling code here:
    for (int i = 0; i < listaEmpregador.length; i++) {
        if (listaEmpregador[i] != null && nomeEmpregadorTexto.getText()
                .toUpperCase().equals(listaEmpregador[i].getNome())) {
                listaEmpregador[i] = null;
                limparTela();
                return;
        }
    }
    
    JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
    }//GEN-LAST:event_excluirEmpregadorButtonActionPerformed

    private void limparTela() {
        nomeEmpregadorTexto.setText(null);
        cpfEmpregadorTexto.setValue(null);
        telefoneEmpregadorTexto.setValue(null);
        emailEmpregadorTexto.setText(null);  
    }

    public Empregador[] getListaEmpregador() {
        return listaEmpregador;
    }

    public void setListaEmpregador(Empregador[] listaEmpregador) {
        this.listaEmpregador = listaEmpregador;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEmpregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroEmpregador cadastroEmpregador = new CadastroEmpregador();
                cadastroEmpregador.setListaEmpregador(MenuPrincipal
                        .getListaEmpregadores());
                cadastroEmpregador.setVisible(true);
                cadastroEmpregador.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton casastrarEmpregadorButton;
    private javax.swing.JLabel cpfEmpregadorLabel;
    private javax.swing.JFormattedTextField cpfEmpregadorTexto;
    private javax.swing.JLabel emailEmpregadorLabel;
    private javax.swing.JTextField emailEmpregadorTexto;
    private javax.swing.JButton excluirEmpregadorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nomeEmpregadorLabel;
    private javax.swing.JTextField nomeEmpregadorTexto;
    private javax.swing.JButton pesquisarEmpregadorButton;
    private javax.swing.JLabel telefoneEmpregadorLabel;
    private javax.swing.JFormattedTextField telefoneEmpregadorTexto;
    // End of variables declaration//GEN-END:variables
}
