/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esocial.userinterface;

import esocial.people.Empregado;
import esocial.people.Empregador;
import esocial.taxes.Guia;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class ConsultarGuiaImposto extends javax.swing.JFrame {

    private Empregador[] listaEmpregadores;
    
    /** Creates new form ConsultarGuiaImposto */
    public ConsultarGuiaImposto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeEmpregadorTexto = new javax.swing.JTextField();
        nomeEmpregadoTexto = new javax.swing.JTextField();
        dataTexto = new javax.swing.JFormattedTextField();
        consultarGuiaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Consultar Guia de Imposto");

        jLabel2.setText("Nome do empregador");

        jLabel3.setText("Nome do empregado");

        jLabel4.setText("Mês/Ano");

        nomeEmpregadorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpregadorTextoActionPerformed(evt);
            }
        });

        try {
            dataTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        consultarGuiaButton.setText("Consultar guia");
        consultarGuiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarGuiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeEmpregadoTexto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultarGuiaButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(consultarGuiaButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeEmpregadorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpregadorTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpregadorTextoActionPerformed

    private void consultarGuiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarGuiaButtonActionPerformed
        Empregador empregador = buscarEmpregador();
        if (empregador != null) {
            Empregado empregado = empregador.buscarEmpregado(nomeEmpregadoTexto
                    .getText());
            if (empregado != null) {
                Guia guia = empregado.buscarGuia((String) dataTexto.getValue());
                if (guia != null) {
                    GuiaImpostoGerada.setGuiasGeradas(new Guia[]{guia});
                    GuiaImpostoGerada.setEmpregadoDeclarado(empregado);
                    GuiaImpostoGerada.setIsGuiasPagasClass(false);
                    GuiaImpostoGerada.main(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Guia não encontrada.");
                    limparTela();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Empregado não encontrado.");
                limparTela();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
            limparTela();
        }
    }//GEN-LAST:event_consultarGuiaButtonActionPerformed

    private Empregador buscarEmpregador() {
        for (Empregador empregador : listaEmpregadores) {
            if (empregador != null && empregador.getNome()
                    .equals(nomeEmpregadorTexto.getText().toUpperCase()))
                return empregador;
        }
        
        return null;
    }
    
    private void limparTela() {
        nomeEmpregadoTexto.setText(null);
        nomeEmpregadorTexto.setText(null);
        dataTexto.setValue(null);
    }
    
    public Empregador[] getListaEmpregadores() {
        return listaEmpregadores;
    }

    public void setListaEmpregadores(Empregador[] listaEmpregadores) {
        this.listaEmpregadores = listaEmpregadores;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarGuiaImposto consultarGuiaImposto = 
                        new ConsultarGuiaImposto();
                consultarGuiaImposto.setListaEmpregadores(MenuPrincipal
                        .getListaEmpregadores());
                consultarGuiaImposto.setVisible(true);
                consultarGuiaImposto.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarGuiaButton;
    private javax.swing.JFormattedTextField dataTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeEmpregadoTexto;
    private javax.swing.JTextField nomeEmpregadorTexto;
    // End of variables declaration//GEN-END:variables

}
