/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esocial.userinterface;

import esocial.people.Empregado;
import esocial.people.Empregador;
import esocial.taxes.Guia;
import esocial.taxes.Imposto;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author rodrigo
 */
public class GerarGuiaImposto extends javax.swing.JFrame {

    private Empregador[] listaEmpregadores;
    private Imposto[] listaImpostos;
    
    /**
     * Creates new form GerarGuiaImposto
     */
    public GerarGuiaImposto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeEmpregadorLabel = new javax.swing.JLabel();
        nomeEmpregadorTexto = new javax.swing.JTextField();
        nomeEmpregadoLabel = new javax.swing.JLabel();
        nomeEmpregadoTexto = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        dataTexto = new javax.swing.JFormattedTextField();
        gerarGuiaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Gerar Guia de Imposto");

        nomeEmpregadorLabel.setText("Nome do empregador");

        nomeEmpregadoLabel.setText("Nome do empregado");

        dataLabel.setText("Mês/Ano");

        try {
            dataTexto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        gerarGuiaButton.setText("Gerar guia");
        gerarGuiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarGuiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeEmpregadorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeEmpregadoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(gerarGuiaButton)))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpregadorLabel)
                    .addComponent(nomeEmpregadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpregadoLabel)
                    .addComponent(nomeEmpregadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabel)
                    .addComponent(dataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(gerarGuiaButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerarGuiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarGuiaButtonActionPerformed
        Empregador empregador = buscarEmpregador();
        if (empregador != null) {
            Empregado empregado = empregador.buscarEmpregado(nomeEmpregadoTexto.getText());
            if (empregado != null) {
                empregado.adicionarImpostos(listaImpostos);

                Guia novaGuia = new Guia((String) dataTexto.getValue(), 
                        empregado.getSalario(), empregado.getListaImpostosCobrados());
                novaGuia.calcularValor();
                if (empregado.adicionarGuia(novaGuia)) {
                    GuiaImpostoGerada.setGuiasGeradas(new Guia[]{novaGuia});
                    GuiaImpostoGerada.setEmpregadoDeclarado(empregado);
                    GuiaImpostoGerada.setIsGuiasPagasClass(false);
                    GuiaImpostoGerada.main(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Guia já existente ou limite de guias atingido.");
                    limparTela();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Empregado não encontrado.");
                limparTela();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Empregador não encontrado.");
            limparTela();
        }
    }//GEN-LAST:event_gerarGuiaButtonActionPerformed

    private Empregador buscarEmpregador() {
        for (Empregador empregador : listaEmpregadores) {
            if (empregador != null && empregador.getNome()
                    .equals(nomeEmpregadorTexto.getText().toUpperCase()))
                return empregador;
        }
        
        return null;
    }
    
    private void limparTela() {
        nomeEmpregadoTexto.setText(null);
        nomeEmpregadorTexto.setText(null);
        dataTexto.setValue(null);
    }
    
    public Empregador[] getListaEmpregadores() {
        return listaEmpregadores;
    }

    public void setListaEmpregadores(Empregador[] listaEmpregadores) {
        this.listaEmpregadores = listaEmpregadores;
    }

    public Imposto[] getListaImpostos() {
        return listaImpostos;
    }

    public void setListaImpostos(Imposto[] listaImpostos) {
        this.listaImpostos = listaImpostos;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarGuiaImposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerarGuiaImposto gerarGuiaImposto = new GerarGuiaImposto();
                gerarGuiaImposto.setListaEmpregadores(MenuPrincipal
                        .getListaEmpregadores());
                gerarGuiaImposto.setListaImpostos(MenuPrincipal
                        .getListaImpostos());
                gerarGuiaImposto.setVisible(true);
                gerarGuiaImposto.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataLabel;
    private javax.swing.JFormattedTextField dataTexto;
    private javax.swing.JButton gerarGuiaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeEmpregadoLabel;
    private javax.swing.JTextField nomeEmpregadoTexto;
    private javax.swing.JLabel nomeEmpregadorLabel;
    private javax.swing.JTextField nomeEmpregadorTexto;
    // End of variables declaration//GEN-END:variables
}
